language: java
jdk:
  - oraclejdk8
deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "ZQTCvku7tTB5zl4hjMJt6GPBZFQHgfxufh24RgNb6lDpv7H3wW+Zo6vR4X72nZVf7uX+Cyq9afJWa3YsFjBpZ1aC0Pq0QUOEMLqT3wNbY8phrUjd7Xz7cl6N6nMFwZrL9N/tXtcsRtl5HzLigYNIvx1Y7dHm1sIZA7nJZIanuWb7r30/tgZkK558ZXlx/VgpPxdBdU1FitRJM8E1hUdQ7cvDwoRSCAoVzEVxEr0u6onuxXhe2i1UTvqHtC+tTImxizyxKtbRxm9RQP5Sw6xKJ20EETqni9gbcu18i+2oCQbYIw9gK4xwXm3LDi/fcnfxW+nUmS2q+8UeTp0d5RNpzD5M3RzI++uVSGPzOXScj2VavOq+/OmAbHptbvIxqnLBmVQZ1xN1gwoG29i5V91LrxPvWPCFTRJ1Bqz7A9O9EDFUiue3ECsV9px9JzpCszobI18ahru4uXzutP9CrRuX2RauGt0gGbO+7jraggXBRv7/tmXf/kcHulw/1g6NTr8/3A5mPuj5Q29jFpCeqwMxkPJgV+I1GzbSLGV2XpdIRncfmefF/75h13B+PqCQCwXW9KSg68ohl925Pkrw17a876QNekz5ATsi3BNkyvcowWkVxjLnlvI9ojkSPu4o0jsQ3m8u7HDCLCubWqI02dwlrU1ThG9gg31a4acpH16qxhw="
  secret_access_key:
    secure: "Kco6KfpvoXgRPwUisfeaUws6oQARVTVaANFjC79fG20kwLK4X2PAfUDAZROBXKLKsg3TQ99FK6UdEQdxFsNSvX4sAg5lCGSpYlmI5Cwb1Iw6jCz3dVot1H0ULb0m6sEoxHlxaeSV7pCj7QD2Tafs1nay27joZ+WypX64dJipkvdIs3n0mxZiXinBk1IWku+V3Rbp6ISCiyYNokmLRevDZZE8xas5WR2LkasJnL1cS7B7LwizacPUISNjdGXNn5keK/EfuGUYGBvS5D6RP1/ImW7D8LMU5aftFSOzjpTxJW1C7wZoQgDUcpxHd0a4hiEfBCZ9ljGkqpmIwuBOVgDmOCYkOXbBTB3oHpENhUnYiQKSwBkhgLKOz/3nUf3UY8hc6SZMEXS5PbQJKOtYDB6otPeJKnMkPt/fKL5qR+b5LbdUwsphf29AC+8i8AQnB7x4+sF6sFL2R6c3Dnou7sqrsAOa5yqDc1mhhFjX6jJY4+EYWW2eBsf0lySi8/gwhiDhsqzrPS2hVVj2DqzFSWGuqBS4JqccOWH3sV+u/FfFxsqgVZMNDlETxMg0DS8v3KopgVnwuR2UUj+ZNMdcrSfzyVRuI69yEh9x48VmlMLzt0thlI+zhOz2M2IRCuISbJG72xsRc7d9UiwAyAncVkXuZCENvtoNa8ULVNWQtMPaDxI="
  region: us-west-2
  app: hannaford-web
  env: hannaford-web-env
  bucket_name: elasticbeanstalk-us-west-2-711033084107
  skip_cleanup: true
  zip_file: target/web-0.0.1-SNAPSHOT.war
  on:
    repo: candrews/hannaford-web
    branch: master
cache:
  directories:
  - $HOME/.m2
